export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Auth
export const AUTH_STARTED_LOADING = 'AUTH_STARTED_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// Profiles
export const PROFILE_STARTED_LOADING = 'PROFILE_STARTED_LOADING';
export const PROFILE_LOADED = 'PROFILE_LOADED';
export const PROFILES_LOADED = 'PROFILES_LOADED';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const PROFILE_CLEAR = 'PROFILE_CLEAR';
export const PROFILE_UPDATED = 'PROFILE_UPDATED';

export const ACCOUTN_DELETED = 'ACCOUNT_DELETED';

export const REPOS_LOADED = 'REPOS_LOADED';

// Posts
export const POST_STARTED_LOADING = 'POST_STARTED_LOADING';
export const POSTS_LOADED = 'POSTS_LOADED';
export const POST_LOADED = 'POST_LOADED';
export const POSTS_ERROR = 'POSTS_ERROR';

export const LIKES_LOADED = 'LIKES_LOADED';

export const COMMENTS_LOADED = 'COMMENTS_LOADED';
